"""Add reminder_email_links join table

Revision ID: 0e080edafd07
Revises: b203060f8cae
Create Date: 2025-06-01 15:08:44.281480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e080edafd07'
down_revision = 'b203060f8cae'
branch_labels = None
depends_on = None


def upgrade():
    # Create the join table
    op.create_table(
        "reminder_email_links",
        sa.Column("reminder_id", sa.Integer(), sa.ForeignKey("reminders.id", name="fk_reminder_email_reminder"), primary_key=True),
        sa.Column("email_message_id", sa.Integer(), sa.ForeignKey("email_messages.id", name="fk_reminder_email_emailmessage"), primary_key=True),
    )

    # Alter the reminders table
    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_message_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "fk_reminders_email_message",  # ← add a name here
            "email_messages",
            ["email_message_id"],
            ["id"],
        )

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('email_message_id')

    op.drop_table('reminder_email_links')
    # ### end Alembic commands ###
