"""Add security_questions table

Revision ID: 433c14034862
Revises: f2fa48d90226
Create Date: 2025-06-16 10:21:06.245753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '433c14034862'
down_revision = 'f2fa48d90226'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('security_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_1', sa.String(length=255), nullable=False),
    sa.Column('answer_1_hash', sa.String(length=255), nullable=False),
    sa.Column('question_2', sa.String(length=255), nullable=False),
    sa.Column('answer_2_hash', sa.String(length=255), nullable=False),
    sa.Column('question_3', sa.String(length=255), nullable=False),
    sa.Column('answer_3_hash', sa.String(length=255), nullable=False),
    sa.Column('set_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('security_questions')
    # ### end Alembic commands ###
