"""Add locked_until to users table

Revision ID: 53de4af4bbdf
Revises: 433c14034862
Create Date: 2025-06-17 09:58:36.494467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53de4af4bbdf'
down_revision = '433c14034862'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('locked_until', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('locked_until')

    # ### end Alembic commands ###
