"""Add reminders feature

Revision ID: b203060f8cae
Revises: d8fbc00da2f2
Create Date: 2025-06-01 09:13:20.594888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b203060f8cae'
down_revision = 'd8fbc00da2f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reminders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('start_at', sa.DateTime(), nullable=False),
    sa.Column('recurrence_rule', sa.String(length=256), nullable=True),
    sa.Column('end_at', sa.DateTime(), nullable=True),
    sa.Column('max_occurrences', sa.Integer(), nullable=True),
    sa.Column('last_sent_at', sa.DateTime(), nullable=True),
    sa.Column('occurrences_sent', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reminder_apprise_links',
    sa.Column('reminder_id', sa.Integer(), nullable=False),
    sa.Column('apprise_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['apprise_id'], ['apprise_urls.id'], ),
    sa.ForeignKeyConstraint(['reminder_id'], ['reminders.id'], ),
    sa.PrimaryKeyConstraint('reminder_id', 'apprise_id')
    )
    op.create_table('reminder_smtp_links',
    sa.Column('reminder_id', sa.Integer(), nullable=False),
    sa.Column('smtp_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['reminder_id'], ['reminders.id'], ),
    sa.ForeignKeyConstraint(['smtp_id'], ['user_mail_settings.id'], ),
    sa.PrimaryKeyConstraint('reminder_id', 'smtp_id')
    )
    op.create_table('reminder_webhook_links',
    sa.Column('reminder_id', sa.Integer(), nullable=False),
    sa.Column('webhook_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['reminder_id'], ['reminders.id'], ),
    sa.ForeignKeyConstraint(['webhook_id'], ['webhooks.id'], ),
    sa.PrimaryKeyConstraint('reminder_id', 'webhook_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reminder_webhook_links')
    op.drop_table('reminder_smtp_links')
    op.drop_table('reminder_apprise_links')
    op.drop_table('reminders')
    # ### end Alembic commands ###
