"""Add mfa_recovery_codes_delivered to User

Revision ID: f2fa48d90226
Revises: f445ab0e9d30
Create Date: 2025-06-05 15:41:51.811567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2fa48d90226'
down_revision = 'f445ab0e9d30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mfa_recovery_codes_delivered', sa.Boolean(), nullable=False, server_default=sa.text('0')))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('mfa_recovery_codes_delivered')

    # ### end Alembic commands ###
