"""Add MFA fields to users

Revision ID: f445ab0e9d30
Revises: 0e080edafd07
Create Date: 2025-06-04 16:42:30.299812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f445ab0e9d30'
down_revision = '0e080edafd07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_reminders_email_message'), type_='foreignkey')
        batch_op.drop_column('email_message_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mfa_enabled', sa.Boolean(), nullable=False, server_default="0"))
        batch_op.add_column(sa.Column('mfa_secret', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('mfa_recovery_codes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('mfa_recovery_codes')
        batch_op.drop_column('mfa_secret')
        batch_op.drop_column('mfa_enabled')

    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_message_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_reminders_email_message'), 'email_messages', ['email_message_id'], ['id'])

    # ### end Alembic commands ###
